### ISSUE TITLE
Vuex integration

### ISSUE THREAD

**Issue by vbrajon** [revue/revue#11]
Vuex is an official Flux adaptation for Vue.

Redux is a particular implementation of Flux.

Do you think it would be appropriate to build Revue on top of Vuex ?

**Comment by egoist** [comment]
Why not use Vuex directly?

**Comment by vbrajon** [comment]
Yep, true.

So I suggest to put a disclamer and prefer vuex use, it is pretty close to redux.

Thanks for the answer :)
