### ISSUE TITLE
If using this syntax (`store.dispatch({type: 'ADD_TODO', this.todo})`)

### ISSUE THREAD

**Issue by dan-gamble** [revue/revue#9]
Sorry this is more of a question.

If i'm using this syntax: `store.dispatch({type: 'ADD_TODO', this.todo})`

And not:

```
      // or use the actionCreator
      store.dispatch(todoActions.addTodo(this.todo))
      // also equal to: (if you binded actions when creating the store)
      const {addTodo} = store.actions
      store.dispatch(addTodo(this.todo))
```

Does that mean i don't have to define any actions in a `actions.js` i can just use `reducers.js`?

**Comment by dan-gamble** [comment]
Nevermind literally just answered my own question by reading the README...

```
// binding the store to Vue instance, actions are optional
const store = new Revue(Vue, reduxStore, actions)
```

Answers it, sorry :)

**Comment by egoist** [comment]
Yes, `actions` are always `action creators` for composing more complex action.

**Comment by dan-gamble** [comment]
One bit of code i have is:

```
    toggleMobileNav () {
      const top = 70 - window.scrollY
      store.dispatch({ type: 'SET_MOBILE_NAV_TOP', top })
      store.dispatch({ type: 'TOGGLE_MOBILE_NAV' })

      this.$emit('overflowBody', this.mobileNav.show)
    }
```

Would you recommend doing this in 1 action instead of on the View model?

**Comment by egoist** [comment]
`{ type: 'SET_MOBILE_NAV_TOP', top }` is exactly already an action.

**Action creators** are functions that return actions because these actions are reusable.

eg:

```js
// addTodo is an action creator
addTodo({title: 'foo'})
/* => return
{
  date: new Date(),
  title: 'foo'
}
*/
addTodo({title: 'bar'})
/* => return
{
  date: new Date(),
  title: 'bar'
}
*/
```

A part of the action (`date`) is just the same (`new Date`) in every action, so we use action creators.

**Compose actions**

Most likely you will use this to compose `async actions`, like ajax call. Being using with [`redux-thunk`](https://github.com/gaearon/redux-thunk) or something alike.

```js
function addTodo() {
  return dispatch => {
    dispatch(addingTodo())
    fetch('xxx.json')
      .then(todo => {
         dispatch(addedTodo(todo))
      })
  }
}
```

**Comment by dan-gamble** [comment]
I think i understand better now, thanks :)

**Comment by egoist** [comment]
Glad to hear that, cheers :beers:

**Comment by dan-gamble** [comment]
:beers: thanks for the plugin :)
